### ISSUE TITLE
Twitch Chat

### ISSUE THREAD

**Issue by AlleyCatzScripts** [ArcaneSpirits/MarbleRace#2]
Hi there i have tryed to get this game to work with my twitch but when i comment in my chat it does not put a marble on the track can you help please i have changed the settings part to twitch and put my channel name in maybe this twitch part can be changed so you have to enter a oArth Code into get it to work with the channel

**Comment by Kronoxis** [comment]
I'm sad to inform you that this project is currently on hold indefinitely. If I ever find the time to pick up from where I left it last year, I'll let you know!

**Comment by AlleyCatzScripts** [comment]
Such a shame this look like it could go some where if it worked right
